package com.paystax.client;

/**
 * @author Erik R. Jensen
 */
public enum PayStaxPermission {
	CREATE_ACCOUNT,
	VIEW_ACCOUNT,
	UPDATE_ACCOUNT,
	DELETE_ACCOUNT,
	CREATE_USER,
	VIEW_USER,
	UPDATE_USER,
	DELETE_USER,
	CREATE_CUSTOMER,
	VIEW_CUSTOMER,
	UPDATE_CUSTOMER,
	DELETE_CUSTOMER,
	CREATE_GATEWAY,
	VIEW_GATEWAY,
	UPDATE_GATEWAY,
	DELETE_GATEWAY,
	CREATE_PAYMENT_METHOD,
	VIEW_PAYMENT_METHOD,
	UPDATE_PAYMENT_METHOD,
	DELETE_PAYMENT_METHOD,
	VIEW_FULL_ACCOUNT_NUMBER,
	CREATE_PAYMENT,
	VIEW_PAYMENT,
	UPDATE_PAYMENT,
	EXECUTE_PAYMENT;
}
